# permissions for end users to view cleanups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cleanup-viewer-role
rules:
- apiGroups:
  - purge.k8s.nan.dev
  resources:
  - cleanups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - purge.k8s.nan.dev
  resources:
  - cleanups/status
  verbs:
  - get
